export const GENRE_RU: Record<string, string> = {
  "Action": "Боевик",
  "Adventure": "Приключения",
  "Award Winning": "Премии",
  "Boys Love": "BL",
  "Comedy": "Комедия",
  "Drama": "Драма",
  "Fantasy": "Фэнтези",
  "Girls Love": "GL",
  "Gourmet": "Кулинария",
  "Horror": "Ужасы",
  "Mystery": "Детектив",
  "Romance": "Романтика",
  "Sci-Fi": "Фантастика",
  "Slice of Life": "Повседневность",
  "Sports": "Спорт",
  "Supernatural": "Сверхъестественное",
  "Suspense": "Триллер",
  "Ecchi": "Этти",
  "Erotica": "Эротика",
  "Hentai": "Хентай",
  "Isekai": "Исекай",
  "Mecha": "Меха",
  "Music": "Музыка",
  "Parody": "Пародия",
  "Psychological": "Психологическое",
  "Samurai": "Самурайский",
  "School": "Школа",
  "Space": "Космос",
  "Vampire": "Вампиры",
  "Magic": "Магия",
  "Military": "Военный",
  "Shounen": "Сёнэн",
  "Shoujo": "Сёдзё",
  "Seinen": "Сэйнэн",
  "Josei": "Дзёсэй",
  "Kids": "Для детей",
  "Anthropomorphic": "Антропоморфный",
  "CGDCT": "Милые девочки",
  "Crossdressing": "Кроссдрессинг",
  "Delinquents": "Хулиганы",
  "Detective": "Детектив",
  "Educational": "Образовательное",
  "Gag Humor": "Гэг-комедия",
  "Gore": "Жестокость",
  "High Stakes Game": "Ставки высоки",
  "Historical": "Историческое",
  "Idols (Female)": "Айдолы",
  "Idols (Male)": "Айдолы",
  "Iyashikei": "Успокаивающее",
  "Love Polygon": "Любовный многоугольник",
  "Martial Arts": "Боевые искусства",
  "Mythology": "Мифология",
  "Organized Crime": "Мафия",
  "Otaku Culture": "Отаку-культура",
  "Performing Arts": "Театр",
  "Pets": "Питомцы",
  "Racing": "Гонки",
  "Reincarnation": "Реинкарнация",
  "Reverse Harem": "Обратный гарем",
  "Romantic Subtext": "Романтический подтекст",
  "Showbiz": "Шоу-бизнес",
  "Strategy Game": "Стратегия",
  "Super Power": "Суперсилы",
  "Survival": "Выживание",
  "Team Sports": "Командный спорт",
  "Time Travel": "Путешествие во времени",
  "Workplace": "Работа",
  "Visual Arts": "Визуальные искусства",
  "Harem": "Гарем",
};

export function translateGenre(genre: string): string {
  return GENRE_RU[genre] ?? genre;
}
